export const TrustbarSectionContent = [
  { number: "5+", label: "Years Experience" },
  { number: "50+", label: "Projects Completed" },
  { number: "25+", label: "Happy Clients" },
  { number: "100%", label: "Client Satisfaction" },
];

export const PricingSectionContent = [
  {
    title: "BASIC",
    price: "$499",
    subtitle: "Single Page Website",
    features: [
      "1–3 Page Custom Website",
      "Responsive Design",
      "Basic SEO Setup",
      "2 Revisions Included",
      "7-Day Delivery",
    ],
    buttonType: "border",
  },
  {
    title: "STARTUP",
    price: "$1,499",
    subtitle: "Multi-Page Website",
    features: [
      "Up to 5 Pages",
      "Custom Development",
      "CMS Integration",
      "3 Revisions Included",
      "14-Day Delivery",
      "Basic Analytics Setup",
    ],
    popular: true,
    buttonType: "solid",
  },
  {
    title: "PROFESSIONAL",
    price: "$2,999",
    subtitle: "Advanced Website",
    features: [
      "Up to 10 Pages",
      "Custom Design & Development",
      "CMS & Plugin Integration",
      "SEO Optimization",
      "5 Revisions Included",
      "21-Day Delivery",
      "Performance & Security Setup",
    ],
    buttonType: "border",
  },
  {
    title: "BUSINESS",
    price: "$5,499",
    subtitle: "Corporate Website",
    features: [
      "Up to 20 Pages",
      "Custom Full-Stack Development",
      "CMS, CRM & API Integrations",
      "Advanced SEO & Analytics",
      "Unlimited Revisions",
      "30-Day Delivery",
      "Dedicated Support",
    ],
    buttonType: "border",
  },
  {
    title: "ENTERPRISE",
    price: "Custom Quote",
    subtitle: "Enterprise Solution",
    features: [
      "Unlimited Pages",
      "Full-Stack Development",
      "Database & API Integrations",
      "E-Commerce & Advanced Features",
      "Unlimited Revisions",
      "45-Day Delivery",
      "Dedicated Project Manager & Support",
    ],
    buttonType: "border",
  },
  {
    title: "CUSTOM SOLUTION",
    price: "Custom Quote",
    subtitle: "Tailored for Your Needs",
    features: [
      "Complete Custom Web & Software Solutions",
      "Unlimited Pages & Features",
      "Custom Integrations & Automation",
      "Advanced Security & Compliance",
      "Unlimited Revisions",
      "Flexible Delivery Timeline",
      "24/7 Dedicated Support",
    ],
    buttonType: "dot",
    popular: true,
  },
];
